name: Build Android APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          validate-wrappers: false

      - name: Install and Build Web
        env:
          APP_VERSION: '1.0.0'
          BUILD_NUMBER: ${{ github.run_number }}
          VITE_BUILD_NUMBER: b${{ github.run_number }}
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build Debug APK
        working-directory: ./android
        env:
          APP_VERSION: '1.0.0'
          BUILD_NUMBER: ${{ github.run_number }}
        run: |
          gradle wrapper --gradle-version 9.5
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Velum-App
          path: android/app/build/outputs/apk/debug/app-debug.apk
